# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Patrick Holmes
# tagline:          'A Jekyll theme'
description:      '<a href="http://roahmlab.com" target="_blank">ROAHM Lab</a> member, Ph.D candidate in Mechanical Engineering at the <a href="https://umich.edu" target="_blank">University of Michigan</a>.'
url:              http://hyde.getpoole.com
baseurl:          /hyde/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

plugins: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

repository: pdholmes/pdholmes.github.io
